PHSHOE-49: Migrate frontend SPA

diff --git a/apps/web/DockerfileDeploy b/apps/web/DockerfileDeploy
--- a/apps/web/DockerfileDeploy
+++ b/apps/web/DockerfileDeploy
@@ -16,13 +16,12 @@ ENV VITE_USER_ACCOUNTS_API_BASE_URL=$VITE_USER_ACCOUNTS_API_BASE_URL
 ENV VITE_CATALOG_API_BASE_URL=$VITE_CATALOG_API_BASE_URL
 
 # Build all widgets and web app
-RUN npm run build
+RUN npm run build && ls -la /repo/apps/web/dist/widgets/ || echo "Widgets not found"
 
 FROM nginx:stable-alpine
 WORKDIR /usr/share/nginx/html
 
 COPY --from=builder /repo/apps/web/dist .
-COPY --from=builder /repo/apps/web/dist/widgets ./widgets
 COPY apps/web/nginx.conf /etc/nginx/conf.d/default.conf
 
 EXPOSE 80
